
TOPDIR=../../
JAR_FILE_NAME=zcs-lib-vnc-common.jar

## list jar files which need to be added to classpath
## (taken from $ZIMBRA_ROOT/lib/jars)
# ZCS_LIB_JARS=

INSTALL_USER=y
INSTALL_ADMIN=y
INSTALL_SERVICE=y
INSTALL_EXTENSION=y

include $(TOPDIR)/zcs-java-lib.mk
